#!/usr/bin/env python

import sys
import getpass
from xenClient import Client


def main(name):
    c = Client()
    if c.delete(name):
        print 'deleted %s' % name
        sys.exit(0)
    else:
        print 'failed to find vm: %s' % name
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        print "usage: %s <vm-to-delete>" % sys.argv[0]
